
# https://docs.docker.com/engine/installation/linux/centos/#install-from-a-package
# https://download.docker.com/linux/centos/7/x86_64/stable/Packages/
# https://yum.dockerproject.org/repo/main/centos/7
# or do 'yum --showduplicates list docker-engine'
docker_versioned_pkg:
  'latest': docker-ce
  '1.13': docker-engine-1.13.1-1.el7.centos
  '17.03': docker-ce-17.03.2.ce-1.el7.centos
  '17.09': docker-ce-17.09.0.ce-1.el7.centos
  '17.12': docker-ce-17.12.1.ce-1.el7.centos
  '18.03': docker-ce-18.03.1.ce-1.el7.centos
  '18.06': docker-ce-18.06.2.ce-3.el7
  '18.09': docker-ce-18.09.5-3.el7
  'stable': docker-ce-18.09.5-3.el7
  'edge': docker-ce-18.09.5-3.el7

docker_selinux_versioned_pkg:
  'latest': docker-ce-selinux
  '1.13': docker-engine-selinux-1.13.1-1.el7.centos
  '17.03': docker-ce-selinux-17.03.2.ce-1.el7.centos
  'stable': docker-ce-selinux-17.03.2.ce-1.el7.centos
  'edge': docker-ce-selinux-17.03.2.ce-1.el7.centos
