# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


- name: Ensure {{rook_ceph_yaml}} folder 
  file:
    path: "{{rook_ceph_yaml}}"
    state: directory
    
- name: "'{{rook_ceph_cluster_name}}': Setup cluster manifest"
  template:
    src: "{{item}}.yaml"
    dest: "/{{rook_ceph_yaml}}/{{item}}.yaml"
  with_items:
  - rbac
  - cluster
  - dashboard_lb
  - blockstorage

- name: "'{{rook_ceph_cluster_name}}': Apply namespace and rbac definition"
  k8s:
    state: present
    src: "{{rook_ceph_yaml}}/rbac.yaml"
  register: rbac_out

#- debug: var=rbac_out

- name: "'{{rook_ceph_cluster_name}}': Apply cluster definition"
  k8s:
    state: present
    src: "{{rook_ceph_yaml}}/cluster.yaml"
  register: cluster_out

#- debug: var=cluster_out

- name: "'{{rook_ceph_cluster_name}}': Wait for rook-ceph-mgr pods to be running"
  k8s_facts:
    api_version: v1
    kind: Pod
    namespace: "{{rook_ceph_cluster_namespace}}"
    label_selectors: 
      - app=rook-ceph-mgr
  register: pods
  until: pods.resources|length() > 0 and pods.resources[0].status.phase == 'Running'
  retries: 600
  delay: 10

- name: "'{{rook_ceph_cluster_name}}': Apply dashboard definition"
  k8s:
    state: present
    src: "{{rook_ceph_yaml}}/dashboard_lb.yaml"
  when: rook_ceph_cluster_dashboard_ip is defined  
  register: dashboard_lb_out


- name: "'{{rook_ceph_cluster_name}}': Create storage classes"
  k8s:
    state: present
    src: "{{rook_ceph_yaml}}/blockstorage.yaml"
  when: rook_ceph_cluster_block_pools is defined and rook_ceph_cluster_block_pools|length() > 0    
  register: blockstorage_out
                      
                      
                      