#####################

# TODO: Update to https://github.com/AerisCloud/ansible-disk


- name: "Install util-linux"
  apt:
    name: '{{ item }}'
    state: 'present'
  with_flattened:
    - 'parted'
  when: disk_additional_disks is defined and disk_additional_disks and ansible_distribution in [ 'Debian', 'Ubuntu' ]
  tags:
    - disk
    - pkgs

- name: "Partition additional disks"
  shell: |
    if
        [ -b {{ item.disk }} ]
    then
        [ -b {{ item.disk }}1 ] || parted --script "{{ item.disk }}" mklabel gpt mkpart primary 1MiB 100%
    fi
  args:
    creates: '{{ item.disk }}1'
    executable: '/bin/bash'
  with_items: "{{disk_additional_disks|default([])}}"
  when: disk_additional_disks is defined  
  tags:
    - disk

- name: Create filesystem on the first partition
  filesystem:
    dev: '{{ item.disk }}1'
    force: '{{ item.force|d(omit) }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.fsopts|d(omit) }}'
  with_items: "{{disk_additional_disks|default([])}}"
  when: disk_additional_disks is defined  
  tags:
    - disk

- name: "Ensure the mount directory exists"
  file: >
    path={{ item.mount }}
    owner={{ disk_user | default('root') }}
    group={{ disk_group | default('root') }}
    state=directory
  with_items: "{{disk_additional_disks|default([])}}"
  when: disk_additional_disks is defined  
  tags:
    - disk

- name: Get UUID for partition
  command: blkid -s UUID -o value "{{ item.disk }}1"
  register: disk_blkid
  with_items: "{{disk_additional_disks|default([])}}"
  when: disk_additional_disks is defined  
  changed_when: False
  tags:
    - disk

- name: "Mount additional disk"
  mount:
    name: '{{ item.0.mount }}'
    fstype: '{{ item.0.fstype }}'
    opts: '{{ item.0.mount_options|d(omit) }}'
    passno: '0'
    src: 'UUID={{ item.1.stdout }}'
    state: '{{ item.0.mount_state|d("mounted") }}'
  when: disk_additional_disks is defined  
  with_together:
    - '{{ disk_additional_disks|default([]) }}'
    - '{{ disk_blkid.results }}'
  tags:
    - disk

    