galaxy_info:
  author: Emilien Kenler <ekenler@wizcorp.jp>
  description: This role allows setting up extra disks and their mount points
  company: Wizcorp K.K.
  license: MIT
  min_ansible_version: 1.8.1
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Debian
      versions:
        - wheezy
        - jessie
    - name: Ubuntu
      versions:
        - all
  categories:
    - system

# TODO: Update to https://github.com/AerisCloud/ansible-disk
