
- name: Populate service facts
  service_facts:
  
#- debug: var=ansible_facts.services

- name: Generate files name from urls
  set_fact:
    register_ca_url_list: "{{ register_ca_url_list|default([]) + [ { 'url': item, 'file': item|replace('https://', '')|replace('http://', '')|replace('/', '_')|replace(':','_') } ] }}"
  with_items: "{{register_ca_urls}}"
  when: register_ca_urls is defined  # Better to fail

- name: Generate files name from path
  set_fact:
    register_ca_path_list: "{{ register_ca_path_list|default([]) + [ { 'src': item, 'file': item|replace('/', '_') } ] }}"
  with_items: "{{register_ca_paths}}"
  when: register_ca_paths is defined  # Better to fail

#- debug: var=register_ca_url_list
#- debug: var=register_ca_path_list

# WARNING Centos/RHEL specifics
- name: Fetch CA certificate from urls
  get_url:
    url: "{{item.url}}"
    dest: "/etc/pki/ca-trust/source/anchors/{{item.file}}"       
    validate_certs: false
  notify: 
  - update_trust_store
  - restart_docker
  when: register_ca_url_list is defined # Will be undefined if register_ca_urls == []
  with_items: "{{register_ca_url_list}}"
  
# WARNING Centos/RHEL specifics
- name: Fetch CA certificate from local path
  copy:
    src: "{{item.src}}"
    dest: "/etc/pki/ca-trust/source/anchors/{{item.file}}"       
  notify: 
  - update_trust_store
  - restart_docker
  when: register_ca_path_list is defined 
  with_items: "{{register_ca_path_list}}"
  
  