
- name: "Kustompatch: Ensure working folder"
  file:
    state: directory
    path: "{{kustompatch_working_folder}}"

- name: "Kustompatch: Fetch source manifests"
  get_url:
    url: "{{kustompatch_src_url}}"
    dest: "{{kustompatch_working_folder}}"

- name: "Kustompatch: Setup kustomization file"
  copy:
    content:
      resources:
      - node.yaml
      patchesStrategicMerge:
      - patch.yaml          
    dest: "{{kustompatch_working_folder}}/kustomization.yaml"

- name: "Kustompatch: Setup patch file"
  copy: 
    content: "{{kustompatch_patch}}"
    dest: "{{kustompatch_working_folder}}/patch.yaml"

- name: "Kustompatch: Generated patched file"
  shell: "{{topolvm_kubectl}} kustomize {{kustompatch_working_folder}} >{{kustompatch_dest}}"
  changed_when: false
  