# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


#----------------------------------------------------------------------- HDFS  

  - name: Install hadoop-hdfs
    yum: pkg=hadoop-hdfs state=present


  - name: Check existing HDFS config
    command: grep {{cluster_id}} /etc/hadoop/conf/core-site.xml
    failed_when: false
    changed_when: false
    register: ret_hdfs
  
#  - debug: var=ret


  - name: Fetch HDFS config
    get_url:
      url: "{{ambari_server_url}}/api/v1/clusters/{{cluster_id}}/services/HDFS/components/HDFS_CLIENT?format=client_config_tar"
      dest: "/tmp/HDFS_CLIENT_CONFIG-{{cluster_id}}.tar"
      force_basic_auth: yes
      url_username: admin
      url_password: admin
      headers: 
        "X-Requested-By" : "ambari"
    when: ret_hdfs.rc != 0 
    
  - name: Deploy HDFS client config in /etc/hadoop/conf       
    unarchive:
      src: "/tmp/HDFS_CLIENT_CONFIG-{{cluster_id}}.tar"
      dest: /etc/hadoop/conf
      remote_src: True
    when: ret_hdfs.rc != 0 
 
  - name: Fix permissions (Due to archive bug) 
    file: path=/etc/hadoop/conf state=directory mode=0755  
  
  
  - name: Remove JAVA_HOME from hadoop-env.sh
    lineinfile:
      dest: /etc/hadoop/conf/hadoop-env.sh
      regexp: "export\\s+JAVA_HOME"
      state: absent
  
  
