
- name: create ssl certificate directory
  file:
    path: /var/private/ssl/ca
    state: directory
    mode: 0755

- name: Deploy CA key in a tmp folder
  copy:
    src: "{{ ca_key_file }}"
    dest: /var/private/ssl/ca/CARoot.key
    mode: 0600

- name: Deploy CA pub cert in a tmp folder
  copy:
    src: "{{ ca_crt_file }}"
    dest: /var/private/ssl/ca/CARoot.crt
    mode: 0600

- name: create ssl certs
  script: scripts/certs-create.sh {{ ca_key_pass }} {{ key_password }} {{ keystore_password }} {{ truststore_password }}
  args:
    chdir: /var/private/ssl

- name: cleanup (1/2)
  file:
    path: /var/private/ssl/ca/CARoot.key
    state: absent

- name: cleanup (2/2)
  file:
    path: /var/private/ssl/ca/CARoot.crt
    state: absent
