


type: map
mapping:
  "docker":
    required: true
    type: map
    mapping:
      "users": 
        type: seq
        sequence:
        - type: str
      "version": { type: str, required: yes }
     