


type: map
mapping:
  "docker":
    required: true
    type: map
    mapping:
      "users": 
        type: seq
        sequence:
        - type: str
      "repo_id": { type: str, required: yes }
      "disabled": { type: bool, required: false }    
     