
schema;node_list:
  type: seq
  required: false
  sequence:
  - type: map
    mapping:
      "name": { type: str, required: true}
      "role": { type: str, required: false}
      "groups":       # Groups can also be defined at node level. Will be added to the ones from the role
        type: seq
        sequence:
        - type: str


type: map
mapping:
  "id": { type: str, required: true, unique: yes }
  "domain": { type: str, required: false, unique: yes }

  "roles":
    type: seq
    required: true
    sequence:
    - type: map
      mapping:
        "name": { type: str, required: true}
        "vcpu": { type: int, required: true}
        "memory": { type: int, required: true}
        "domain": { type: str, required: false, unique: yes }
        "nodes":
          include: node_list
        "groups":       # defaut value is an array of a single element with role name. (Will create an ansible group with this role name). Set groups: [] if you do not want an ansible group of this role.
          type: seq
          sequence:
          - type: str


  "nodes":
    include: node_list

    