# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.

- name: Create certificate location
  file: path=/etc/elasticsearch/certs state=directory owner=elasticsearch group=elasticsearch mode="0700"

- name: Copy certificates to location
  copy:
    src=certs/{{inventory_hostname}}/{{inventory_hostname}}.p12
    dest=/etc/elasticsearch/certs/{{inventory_hostname}}.p12

- name: Configure certificate in Elastic
  blockinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK (SSL_CERT)"
    block: |
      xpack.security.http.ssl.enabled: true
      xpack.security.http.ssl.keystore.path: certs/{{inventory_hostname}}.p12 
      xpack.security.http.ssl.truststore.path: certs/{{inventory_hostname}}.p12 
  notify:
  - restart elasticsearch
    
    
  
  