---
- name: restart docker
  command: /bin/true
  listen: restart_docker
  notify:
    - Docker | reload systemd
    - Docker | reload docker
    - Docker | wait for docker

- name: Docker | reload systemd
  systemd:
    daemon_reload: true

- name: Docker | reload docker
  service:
    name: docker
    state: restarted

- name: Docker | wait for docker
  command: "/bin/docker images"
  register: docker_ready
  retries: 20
  delay: 1
  until: docker_ready.rc == 0

# WARNING Centos/RHEL specifics
- name: Update trust store  
  listen: update_trust_store
  shell: update-ca-trust extract
  
  
  