kafka:
  broker:
    user: cp-kafka
    group: confluent
    config_file: /etc/kafka/server.properties
    systemd_file: /usr/lib/systemd/system/confluent-kafka.service
    systemd_override: /etc/systemd/system/confluent-kafka.service.d
    service_name: confluent-kafka
    systemd:
      enabled: yes
      state: started
    environment:
      KAFKA_HEAP_OPTS: "-Xmx1g"
    config:
      zookeeper.set.acl: "false"
      group.initial.rebalance.delay.ms: 0
      log.retention.check.interval.ms: 300000
      log.retention.hours: 168
      log.segment.bytes: 1073741824
      num.io.threads: 16
      num.network.threads: 8
      num.partitions: 1
      num.recovery.threads.per.data.dir: 2
      offsets.topic.replication.factor: 3
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 102400
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
      zookeeper.connection.timeout.ms: 6000
      metric.reporters: null
      confluent.metrics.reporter.bootstrap.servers: null
#      Override this when using confluent entreprise edition
#     metric.reporters: io.confluent.metrics.reporter.ConfluentMetricsReporter
#     confluent.metrics.reporter.bootstrap.servers: "{{inventory_hostname}}:{{broker.config.port}}"
      confluent.metrics.reporter.topic.replicas: 3
      ssl.endpoint.identification.algorithm: ""
      confluent.metrics.reporter.ssl.endpoint.identification.algorithm: ""


zookeeper:
  user: cp-kafka
  group: confluent
  config_file: /etc/kafka/zookeeper.properties
  service_name: confluent-zookeeper
  systemd_override: /etc/systemd/system/confluent-zookeeper.service.d
  config:
    clientPort: 2181
    maxClientCnxns: 0
    initLimit: 5
    syncLimit: 2
    autopurge.snapRetainCount: 10
    autopurge.purgeInterval: 1
    dataDir: /var/lib/zookeeper
    jaasLoginRenew: 3600000
    kerberos.removeHostFromPrincipal: "true"
    kerberos.removeRealmFromPrincipal: "true"

  environment:
    KAFKA_HEAP_OPTS: "-Xmx1000M"
    LOG_DIR: /var/log/zookeeper
  systemd:
    enabled: yes
    state: started

