# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.

type: map
mapping:
  "aws_key_pairs":
    type: seq
    required: false
    sequence:
    - type: map
      mapping:
        key_pair_id: { type: str, required: true } 
        key_pair_name: { type: str, required: true }
        private_key_path: { type: str, required: false }
  
  "routes53":
    type: seq
    required: false
    sequence:
    - type: map
      mapping:
        route53_id: { type: str, required: true } 
        forward_domain: { type: str, required: true }
        reverse_domain: { type: str, required: true }
  
  "infras":
    type: seq
    required: false
    sequence:
    - type: map
      mapping:
        "name": { type: str, required: true }
        "region": { type: str, required: true }
        "profile_by_user":
          type: seq
          required: true
          sequence:
          - type: map
            mapping:
              "login": { type: str, required: true }
              "profile": { type: str, required: true }
        "route53":
          type: map
          required: true
          mapping:
            "forward_domain": { type: str, required: true }
            "reverse_domain": { type: str, required: true }
        "subnet_aliases":
          type: seq
          required: false
          sequence:
          - type: map
            mapping:
              "name": { type: str, required: true }
              "alias": { type: str, required: true }
        "key_pair":
          type: map
          required: true
          mapping:
            "name": { type: str, required: true }
            "private_key_path_by_user":
              type: seq
              required: true
              sequence:
              - type: map
                mapping:
                  "login": { type: str, required: true }
                  "path": { type: str, required: true }
          
            
  "amazon_machine_images":
    type: seq
    required: false
    sequence:
    - type: map
      mapping:
        "name": { type: str, required: true }
        "ssh_user": { type: str, required: true }
        "ami_by_region":
          type: seq
          required: true
          sequence:
          - type: map
            mapping:
              "region": { type: str, required: true }
              "ami_id": { type: str, required: true }
            
        
        
        