# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.

schema;node_list:
  type: seq
  required: false
  sequence:
  - type: map
    mapping:
      "aws":
        type: map
        required: true
        mapping:
          "subnet": { type: str, required: true }
          "tags":
            type: map
            required: false
            mapping:
              regex;(.*):
                type: str
          

type: map
mapping:
  "selinux": { type: str, required: true, enum: ["disabled", "enforcing", "permissive"] }
  "aws":
    type: map
    required: true
    mapping:
      "infra": { type: str, required: true }
      "owner": { type: str, required: true }
      "ami": { type: str, required: false }
      "security_groups": 
        type: seq
        required: false
        sequence:
        - type: map
          mapping:
            "name":  { type: str, required: true }
            "description":  { type: str, required: false }
            "tags":
              type: map
              required: false
              mapping:
                regex;(.*):
                  type: str
            "inbound_rules":
              type: seq
              required: false
              sequence:
              - type: map
                mapping:
                  "description": { type: str, required: false }
                  "protocol": { type: str, required: true } 
                  "port": { type: any, required: false }   
                  "from_port": { type: int, required: false }   
                  "to_port": { type: int, required: false }   
                  "icmp_type": { type: str, required: false }
                  "icmp_code": { type: int, required: false }
                  "source": { type: str, required: true }   
            "outbound_rules":
              type: seq
              required: false
              sequence:
              - type: map
                mapping:
                  "description": { type: str, required: false }
                  "protocol": { type: str, required: true } 
                  "port": { type: any, required: false }   
                  "from_port": { type: int, required: false }   
                  "to_port": { type: int, required: false }   
                  "icmp_type": { type: str, required: false }
                  "icmp_code": { type: int, required: false }
                  "destination": { type: str, required: true }   
      "network_load_balancers":
        type: seq
        required: false
        sequence:
        - type: map
          mapping:
            "name":  { type: str, required: true }
            "description":  { type: str, required: false }
            "tags":
              type: map
              required: false
              mapping:
                regex;(.*):
                  type: str
            "aliases":
              type: seq
              required: false
              sequence:
              - type: str
            "subnets":
              type: seq
              required: true
              sequence:
              - type: str
            "listeners":
              type: seq
              required: true
              sequence:
              - type: map
                mapping:
                  "port": { type: int, required: true }
                  "target_port": { type: int, required: true }
                  "target_group": { type: str, required: true }
            
          
        
        
        
        
        
        
        
  "roles": 
    type: seq
    required: true
    sequence:
    - type: map
      mapping:
        "aws":
          type: map
          required: true
          mapping:
            "ami": { type: str, required: false }
            "instance_type": { type: str, required: true }
            "root_type": { type: str, required: false, enum: ["standard", "gp2", "io1", "sc1", "st1"] }  # default: gp2   
            "security_group": { type: str, required: true }   
            "create_instance_role": { type: bool, required: false }   # Default: false
            "instance_role_name": { type: str, required: false }    # Default to "<clusterId>_<role>_instance"
            "tags":
              type: map
              required: false
              mapping:
                regex;(.*):
                  type: str
        "root_size": { type: int, required: true }   
        "swap_size": { type: int, required: true }   
        "data_disks":
          type: seq 
          required: false
          sequence:
          - type: map
            mapping:
              "size": { type: int, required: true }
              "mount": { type: str, required: false }
              "device": { type: str, required: false }      # Default to TODO   
              "device_aws": { type: str, required: false }  # default to "device"   
              "device_host": { type: str, required: false } # default to "device"  
              "type": { type: str, required: false, enum: ["standard", "gp2", "io1", "sc1", "st1"] }  # default: gp2   
          
          
          
  