



es_java_install: False
es_api_port: 9200
es_config:
  network.host: "{{ ansible_fqdn }}"
  http.port: 9200
  transport.tcp.port: 9300
  bootstrap.memory_lock: false
es_scripts: false
es_templates: false
es_version_lock: false
es_api_host: "{{ ansible_fqdn }}"

# There is two reasons to use a package url:
# - It could be faster if the repo is local
# - Seems yum install is bugged on current role:  
#     TASK [ansible-elasticsearch : RedHat - Install Elasticsearch] **************************************************************************************************
#     fatal: [w2]: FAILED! => {"msg": "The conditional check 'redhat_elasticsearch_install_from_repo.rc == 0' failed. The error was: error while evaluating conditional (redhat_elasticsearch_install_from_repo.rc == 0): 'dict object' has no attribute 'rc'"}  
es_use_repository: False
es_custom_package_url: "{{repo_misc_base_url }}/elasticsearch-{{ es_version }}.rpm"
