# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.




es_java_install: False
es_api_port: 9200
es_config:
  network.host: "{{ ansible_fqdn }}"
  http.port: 9200
  transport.tcp.port: 9300
  bootstrap.memory_lock: false
  cluster.name: "{{ cluster_id }}"
  discovery.zen.ping.unicast.hosts: '{% for host in groups["masters"] %}{% if not loop.first %},{% endif %}{{  hostvars[host]["ansible_fqdn"] }}:9300{% endfor %}'
  node.name: "{{ansible_fqdn}}-{{es_instance_name}}"
es_scripts: false
es_templates: false
es_version_lock: false
es_api_host: "{{ ansible_fqdn }}"

# There is two reasons to use a package url:
# - It could be faster if the repo is local
# - Seems yum install is bugged on current role:  
#     TASK [ansible-elasticsearch : RedHat - Install Elasticsearch] **************************************************************************************************
#     fatal: [w2]: FAILED! => {"msg": "The conditional check 'redhat_elasticsearch_install_from_repo.rc == 0' failed. The error was: error while evaluating conditional (redhat_elasticsearch_install_from_repo.rc == 0): 'dict object' has no attribute 'rc'"}  
es_use_repository: False
es_custom_package_url: "{{repo_misc_base_url }}/elasticsearch-{{ es_version }}.rpm"
