

type: map
mapping:
  "elasticsearch":
    type: map
    required: true
    mapping:
      "repo_id": { type: str, required: true }
      "disabled": { type: bool, required: false }
      "playbook_vars": 
        type: any
  "roles":
    type: seq
    required: true
    sequence:
    - type: map
      mapping:
        "elasticsearch":
          type: map
          mapping: 
            "playbook_vars":
              type: any
            "nodes":
              type: seq
              required: false
              sequence:
              - type: any
#    