- name: ksql create group
  group:
    name: "{{ksql.group}}"
- name: ksql create user
  user:
    name: "{{ksql.user}}"
    comment: "Connect Distributed User"
    system: yes
    group: "{{ksql.group}}"
- name: ksql create config
  template:
    src: ksql.properties.j2
    dest: "{{ksql.config_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  when: security_mode == "plaintext"
  notify:
    - restart ksql
- name: ksql create config
  template:
    src: ksql_ssl.properties.j2
    dest: "{{ksql.config_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  when: security_mode == "ssl"
  notify:
    - restart ksql
- name: ksql create config
  template:
    src: ksql_sasl_ssl.properties.j2
    dest: "{{ksql.config_file}}"
    mode: 0640
    owner: "{{ksql.user}}"
    group: "{{ksql.group}}"
  when: security_mode == "sasl_ssl"
  notify:
    - restart ksql
- name: ksql configure service
  systemd:
    name: "{{ksql.service_name}}"
    enabled: "{{ksql.systemd.enabled}}"
    state: "{{ksql.systemd.state}}"    
