# Copyright (C) 2020 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


- name: Populate service facts
  service_facts:
   
- name: Stop lvmd services
  service:
    name: lvmd
    enabled: no
    state: stopped        
  when: "'lvmd.service' in ansible_facts.services"
            
- name: Remove the lvmd binary
  file:
    path:  /opt/sbin/lvmd
    state: absent

- name: Remove the lvmd config folder
  file:
    path:  /etc/topolvm
    state: absent

- name: Remove lvmd service
  file:
    path: /usr/lib/systemd/system/lvmd.service
    state: absent
  notify: reload_service_file
    