



type: map
mapping:
  "hortonworks":
    required: true
    type: map
    mapping:
      "ansible_repo_folder": { type: str, required: yes }
  "repositories":
    type: map
    required: true
    mapping:
      "hortonworks": 
        type: seq
        required: true
        sequence:
        - type: map
          mapping:
            "repo_id": { type: str, required: True }
            "ambari_version": { type: str, required: True }
            "hdp_version": { type: str, required: True }
            "hdf_version": { type: str, required: True }
            "repo_base_url": { type: str, required: True }
            
                                  
    
    
    
  
