zookeeper:
  config:
    clientPort: 2181
broker:
  config:
    port: 9092
confluent:
  package_name: confluent-platform-2.11
  repository:
    debian:
    redhat:
      main:
        baseurl: https://packages.confluent.io/rpm/5.0
        gpgcheck: 1
        gpgkey: https://packages.confluent.io/rpm/5.0/archive.key
        enabled: 1
      dist:
        baseurl: https://packages.confluent.io/rpm/5.0/7
        gpgcheck: 1
        gpgkey:  https://packages.confluent.io/rpm/5.0/archive.key
        enabled: 1
