
{% if rook_ceph_cluster_block_pools is defined and rook_ceph_cluster_block_pools|length() > 0 %}
{% for bp in rook_ceph_cluster_block_pools %}
---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: {{bp.name}}
  namespace: {{rook_ceph_cluster_name}}
spec:
  failureDomain: host
  replicated:
    size: {{ bp.replication }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: {{ bp.storage_class_name }}
provisioner: ceph.rook.io/block
parameters:
  blockPool: {{bp.name}}
  # The value of "clusterNamespace" MUST be the same as the one in which your rook cluster exist
  clusterNamespace: {{rook_ceph_cluster_name}}
  # Specify the filesystem type of the volume. If not specified, it will use `ext4`.
  fstype: xfs
# Optional, default reclaimPolicy is "Delete". Other options are: "Retain", "Recycle" as documented in https://kubernetes.io/docs/concepts/storage/storage-classes/
reclaimPolicy: {{bp.reclaim_policy}}
{% endfor %}
{% endif %}
