# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.



- name: Install k8s ansible module required package
  yum: 
    name: python2-openshift 
    state: present
  
- name: Copy definition file
  template:
    src: metallb_{{ metallb_version }}.yaml
    dest: /tmp/metallb.yaml  

- name: Copy configuration file
  template:
    src: metallb-config.yaml
    dest: /tmp/metallb-config.yaml  
       
- name: Install metallb
  k8s:
    state: present
    src: "/tmp/metallb.yaml"
    
- name: Test if secret is created
  k8s_info:
    api_version: v1
    kind: Secret
    name: memberlist
    namespace: metallb-system
  register: mlb_secret
  changed_when: false

- block:
  - name: generate secret
    shell: openssl rand -base64 128 | tr -d '\n'
    register: secret_data
  
  # - debug: var=secret_data  
  
  - name: Generate secret manifest
    template:
      src: memberList.yaml
      dest: /tmp/memberList.yaml  
  
  - name: Apply secret manifest
    k8s:
      state: present
      src: /tmp/memberList.yaml
  when: mlb_secret.resources|length == 0 

  
- name: Configure metallb
  k8s:
    state: present
    src: "/tmp/metallb-config.yaml"
        