confluent:
  control:
    center:
      user: cp-control-center
      group: confluent
      config_file: /etc/confluent-control-center/control-center-production.properties
      service_name: confluent-control-center
      config:
        confluent.controlcenter.streams.num.stream.threads: 8
        confluent.controlcenter.data.dir: /var/lib/confluent/control-center
        confluent.controlcenter.streams.ssl.endpoint.identification.algorithm: ""
        confluent.controlcenter.rest.ssl.endpoint.identification.algorithm: ""
      systemd:
        enabled: yes
        state: started
