# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


type: map
mapping:
  "k8s":
    type: map
    required: true
    mapping:
      "storage_classes":
        type: seq
        required: true
        sequence:
        - type: map
          mapping:
            "name": { type: str, required: true }
            "type": { type: str, required: true, enum: [ "local_static" ] }
            "reclaim_policy": { type: str, required: true, enum: [ "Delete", "Retain" ] }

  "roles": 
    type: seq
    required: true
    sequence:
    - type: map
      mapping:
        "data_disks":
          type: seq 
          required: false
          sequence:
          - type: map
            mapping:
              "ref": { type: str, required: false }
        "k8s":
          type: map
          required: false
          mapping:
            "local_static_pv":
              type: seq
              required: false
              sequence:
              - type: map
                mapping: 
                  "host_dir": { type: str, required: true }
                  "storage_class": { type: str, required: true }
                  "sources":
                    type: seq
                    required: true
                    sequence:
                    - type: map
                      mapping:
                        "folder": { type: str, required: false }
                        "count": { type: int, required: false }
                        "data_disk_ref": { type: str, required: false }
                        "splits": { type: seq, required: false, sequence: [ { type: int } ] }
          
          
          