- name: schema-registry create group
  group:
    name: "{{schema.registry.group}}"
- name: schema-registry create user
  user:
    name: "{{schema.registry.user}}"
    comment: "Schema Registry User"
    system: yes
    group: "{{schema.registry.group}}"
- name: schema-registry create config
  template:
    src: schema-registry.properties.j2
    dest: "{{schema.registry.config_file}}"
    mode: 0640
    owner: "{{schema.registry.user}}"
    group: "{{schema.registry.group}}"
  when: security_mode == "plaintext"
  notify:
    - restart schema-registry
- name: schema-registry create config
  template:
    src: schema-registry_ssl.properties.j2
    dest: "{{schema.registry.config_file}}"
    mode: 0640
    owner: "{{schema.registry.user}}"
    group: "{{schema.registry.group}}"
  when: security_mode == "ssl"
  notify:
    - restart schema-registry
- name: schema-registry create config
  template:
    src: schema-registry_sasl_ssl.properties.j2
    dest: "{{schema.registry.config_file}}"
    mode: 0640
    owner: "{{schema.registry.user}}"
    group: "{{schema.registry.group}}"
  when: security_mode == "sasl_ssl"
  notify:
    - restart schema-registry
- name: schema-registry configure service
  systemd:
    name: "{{schema.registry.service_name}}"
    enabled: "{{schema.registry.systemd.enabled}}"
    state: "{{schema.registry.systemd.state}}"
