- name: kafka-rest create group
  group:
    name: "{{kafkarest.group}}"
- name: kafka-rest create user
  user:
    name: "{{kafkarest.user}}"
    comment: "Kafka REST User"
    system: yes
    group: "{{kafkarest.group}}"
- name: kafka-rest create config
  template:
    src: kafka-rest.properties.j2
    dest: "{{kafkarest.config_file}}"
    mode: 0640
    owner: "{{kafkarest.user}}"
    group: "{{kafkarest.group}}"
  when: security_mode == "plaintext"
  notify:
    - restart kafka-rest
- name: kafka-rest create config
  template:
    src: kafka-rest_ssl.properties.j2
    dest: "{{kafkarest.config_file}}"
    mode: 0640
    owner: "{{kafkarest.user}}"
    group: "{{kafkarest.group}}"
  when: security_mode == "ssl"
  notify:
    - restart kafka-rest
- name: kafka-rest create config
  template:
    src: kafka-rest_sasl_ssl.properties.j2
    dest: "{{kafkarest.config_file}}"
    mode: 0640
    owner: "{{kafkarest.user}}"
    group: "{{kafkarest.group}}"
  when: security_mode == "sasl_ssl"
  notify:
    - restart kafka-rest
- name: kafka-rest configure service
  systemd:
    name: "{{kafkarest.service_name}}"
    enabled: "{{kafkarest.systemd.enabled}}"
    state: "{{kafkarest.systemd.state}}"
