# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


type: map
mapping:
  "docker_nexus_proxy":
    type: map
    required: True
    mapping:
      "disabled": { type: bool, required: false }
      "nexus_version": { type: str, required: true }
      "nexus_download_folder_url": { type: str, required: true }
      "nexus_default_port": { type: int, required: false }    # Default: 8081
      "nexus_admin_password": { type: str, required: true }
      "nexus_internal_docker_port": { type: int, required: false }  # Default: 8082
      "next_proxy_id": { type: str, required: false }

