# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


- name: Create user 'cerebro'
  user: name=cerebro

- name: Download/untar package
  unarchive: src={{cerebro_rpm_url}} dest=/opt remote_src=yes
  
- name: Set appropriate permissions
  file: dest=/opt/cerebro-{{cerebro_version}} owner=cerebro group=cerebro recurse=yes
  
- name: Disable SSL certificate check
  blockinfile:
    path: /opt/cerebro-{{cerebro_version}}/conf/application.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK (SSL_UNCHECK)"
    block: |
      play.ws.ssl.loose.acceptAnyCertificate=true
  notify:
  - restart cerebro
  when: not cerebro_validate_certs
    

- name: Create cerebro service
  template:
    src: cerebro.service.j2
    dest: /usr/lib/systemd/system/cerebro.service
    owner: root
    group: root
    mode: 0644
    backup: no
  notify:
  - reload service file      
  - restart cerebro


# ------------------------------------ Service activate and start   
- meta: flush_handlers
   
- name: Enable cerebro services
  service:
    name: cerebro
    enabled: yes
    state: started        
      