# Copyright (C) 2018 BROADSoftware
#
# This file is part of EzCluster
#
# EzCluster is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EzCluster is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with EzCluster.  If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.


type: map
mapping:
  "ansible":
    type: map
    required: false
    mapping:
      "disabled": { type: bool, required: false }    
      "playbooks":
        type: seq
        required: false
        sequence:
        - type: map
          mapping:
            file: { type: str, required: true }
            "tags": { type: seq, required: false, sequence: [ { type: str } ] }
      "roles_paths":
        type: seq
        required: false
        sequence:
        - type: str 
      "roles_paths_from_plugins":
        type: seq
        required: false
        sequence:
        - type: str 
      "roles":
        type: seq
        required: false
        sequence:
        - type: map
          mapping:
            "name": { type: str, required: true } 
            "scope": { type: str, required: true } 
            "tags": { type: seq, required: false, sequence: [ { type: str } ] }
            "vars":
              type: any
        