
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: koo-directory-editor-{{ koomgr_admin_group }}
  namespace: koo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koo-directory-editor
subjects:
- apiGroup: rbac.authorization.k8s.io 
  kind: Group
  name: {{ koomgr_admin_group }}
  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: koo-token-editor-{{ koomgr_admin_group }}
  namespace: koo-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: koo-token-editor
subjects:
- apiGroup: rbac.authorization.k8s.io 
  kind: Group
  name: {{ koomgr_admin_group }}

---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: koo-serving-cert
  namespace: koo-system
spec:
  dnsNames:
  - koo-webhook-service.koo-system.svc
  - koo-webhook-service.koo-system.svc.cluster.local
{% for node in groups["kube-master"] %}
  - {{hostvars[node].ansible_nodename }}
{% endfor %}  
{% if koomgr_domains is defined %}
{% for domain in koomgr_domains %}
{% for node in groups["kube-master"] %}
  - {{hostvars[node].ansible_nodename }}.{{domain}}
{% endfor %}  
{% endfor %}  
{% endif %}
  issuerRef:
    kind: Issuer
    name: koo-selfsigned-issuer
  secretName: webhook-server-cert
  