# Kubernetes API version
apiVersion: v1
# kind of the API object
kind: Config
# clusters refers to the remote service.
clusters:
  - name: koosrv
    cluster:
      certificate-authority: /etc/pki/ca-trust/source/anchors/ca1_broadsoftware_com.crt         # CA for verifying the remote service.
      server: https://{{koosrv_hostname}}:{{koosrv_nodeport}}/validateToken # URL of remote service to query. Must use 'https'.

# users refers to the API server's webhook configuration.
users:
  - name: kooapisrv
#    user:
#      client-certificate: /etc/kubernetes/koo/kooapisrv.crt # cert for the webhook plugin to use
#      client-key: /etc/kubernetes/koo/kooapisrv.key          # key matching the cert

# kubeconfig files require a context. Provide one for the API server.
current-context: webhook
contexts:
- context:
    cluster: koosrv
    user: kooapisrv
  name: webhook

